name: Build and Release

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Build and Package
      run: make all

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-artifacts
        path: dist/*

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} dist/* --generate-notes
